{{- if not (.Values.isDBAAS) }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jpetstoredb
  labels:
    app: jpetstoredb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpetstoredb
  template:
    metadata:
      labels:
        app: jpetstoredb
    spec:
      containers:
      - name: jpetstoredb
        image: "{{ .Values.image.repository }}/jpetstoredblocal:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql.password
          - name: MYSQL_USER
            valueFrom:
                secretKeyRef:
                  name: mysql-creds
                  key: mysql.username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql.password
{{- end }}